### ISSUE TITLE
iphone 7 plus 预览时发现的问题

### ISSUE THREAD

**Issue by jeaxnew** [hx-dl/bicycle#1]
1 底部“扫码解锁”不显示，貌似被map给覆盖掉了。
2 打开小程序定位后，定位动态变化，再次按右下角的定位到当前位置时，小图标调到当前位置后，过1秒左右，又跳回到打开小程序时的初始定位位置。
（荣耀v8测试没有发现以上问题。）

小程序非常精美，感谢分享。

**Comment by hx-dl** [comment]
iPhone还没有测试过哈，如果有覆盖问题，定位问题，大概跟环境有关，青据单车官方的偶尔也会有这个定位的问题，把首页的扫码解锁按钮改成cover-view提高层级就可以解决覆盖问题，我回头抽时间试试
